name: groupscholar_cohort_snapshotter
description: Cohort snapshot capture and reporting CLI for Group Scholar.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.9

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  csv: ^6.0.0
  path: ^1.9.0
  postgres: ^3.4.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
